### ISSUE TITLE
Embed META

### ISSUE THREAD

**Issue by JakeLion** [NightZan999/nightzan999.github.io#1]
Definitely take advantage of the meta embed capabilities, this allows services like discord to embed your webpage whenever you send the link in any chat.

If you want I can create a PR with some embed meta, but just thinking you should take advantage of that.

**Comment by NightZan999** [comment]
Hmm, very good idea @JakeLion. Thanks for the suggestion so, I ~~might google this up~~
I have uhh never actually created embeds for discord or any other such platform. 

Can you make a PR for the same since this isn't actually that big of a change. Show me what the output would be in discord. That way I can maybe edit the meta tags

I can see this pretty much as part of the website!

**Comment by JakeLion** [comment]
Ok ill make a PR
